### postgres

In [ ]:
"postgresql://dwopt_tester:1234@localhost/dwopt_test"

In [12]:
from pathlib import Path

(Path.home() / 'global-bundle.pem').as_posix()

'C:/Users/yzdom/global-bundle.pem'

In [14]:
import psycopg2
import boto3

password = "12345678"

conn = None
try:
    conn = psycopg2.connect(
        host='database-1.cgdws00gohmv.us-east-1.rds.amazonaws.com',
        port=5432,
        database='postgres',
        user='postgres',
        password=password,
        sslmode='verify-full',
    sslrootcert='C:/Users/yzdom/global-bundle.pem'
    )
    cur = conn.cursor()
    cur.execute('SELECT version();')
    print(cur.fetchone()[0])
    cur.close()
except Exception as e:
    print(f"Database error: {e}")
    raise
finally:
    if conn:
        conn.close()

Database error: could not translate host name "database-1.cgdws00gohmv.us-east-1.rds.amazonaws.com" to address: Name or service not known

OperationalError: could not translate host name "database-1.cgdws00gohmv.us-east-1.rds.amazonaws.com" to address: Name or service not known

### teradata

set up clearscape

https://clearscape.teradata.com/dashboard

In [21]:
import teradatasql
import os

conn = teradatasql.connect(
    host='test-l36lujzkc0420a7n.env.clearscape.teradata.com',
    user='demo_user',
    password=os.getenv('password'),
)
cur = conn.cursor()
cur.execute("select * from dbc.dbcinfo where infokey = 'Version'")
_ = cur.fetchone()
print(_)
cur.close()

['VERSION', '20.00.24.60']

In [22]:
import sqlalchemy as alc
import pandas as pd
import os


# add run method to engine
def run(self: alc.engine.Engine, sql: str) -> pd.DataFrame | None:
    with self.begin() as conn:
        res = conn.execute(alc.text(sql))
        if res.returns_rows:
            return pd.DataFrame(res.all(), columns=res.keys())


alc.engine.Engine.run = run

connection_string = f"teradatasql://demo_user:{os.environ['password']}@test-l36lujzkc0420a7n.env.clearscape.teradata.com"
eng = alc.create_engine(connection_string)

In [23]:
_ = eng.run(f"select * from dbc.dbcinfo where infokey = 'Version'")
_

   InfoKey     InfoData
0  VERSION  20.00.24.60

In [ ]:
df = eng.run(
    f"""
select *
from dbc.dbcinfo
where infokey = 'Version'
"""
)
df

   InfoKey     InfoData
0  VERSION  17.20.03.26

In [ ]:
qry = f"""
select
    *
from dbc.dbcinfo
where infokey = 'Version'
"""

df = eng.run(qry)
df

   InfoKey     InfoData
0  VERSION  17.20.03.26

In [ ]:
_ = eng.run("select top 5 * from dbc.dbcinfo")
print(_.head().to_string())

                 InfoKey     InfoData
0                VERSION  17.20.03.26
1                RELEASE  17.20.03.26
2  LANGUAGE SUPPORT MODE     Standard

In [ ]:
eng.run("select count(*) as n from dbc.dbcinfo").iloc[0, 0]

np.int64(3)

In [ ]:
qry = f"""
select
    infokey,
    count(1) as n
from dbc.dbcinfo
where infokey = 'Version'
group by 1
order by 1
"""

df = eng.run(qry)
df

   InfoKey  n
0  VERSION  1

In [ ]:
tbl = "tmp_tbl"

try:
    eng.run(f"drop table {tbl}")
except Exception as e:
    pass

_ = eng.run(
    f"""
create table {tbl} as (
    select *
    from dbc.dbcinfo
) with data;


"""
)

for qry in f"""
select count(*) from {tbl};

drop table {tbl};
""".split(
    ";"
):
    qry = qry.strip()
    if qry:
        res = eng.run(qry)
        if res is not None:
            print(res)

   Count(*)
0         3
Empty DataFrame
Columns: []
Index: []

### oracle

In [ ]:
import pandas as pd
import sqlalchemy as alc


# add run method to engine
def run(self, sql):
    with self.begin() as conn:
        res = conn.execute(alc.text(sql))
        if res.returns_rows:
            return pd.DataFrame(res.all(), columns=res.keys())


alc.engine.Engine.run = run

# url

url_base = "dwopt_test:1234@localhost:1521/?service_name=XEPDB1 &encoding=UTF-8&nencoding=UTF-8"

# use just oracle
url = f"oracle://{url_base}"
eng = alc.create_engine(url, echo=True)

eng.dialect.name
eng.dialect.driver

eng.run("select * from dual")


# oracledb
url = f"oracle+oracledb://{url_base}"
bin_path = r"C:\app\User\product\21c\dbhomeXE\bin"
eng = alc.create_engine(url, echo=True, thick_mode={"lib_dir": bin_path})

eng.dialect.driver

eng.run("select * from dual")